name: bcd_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.0+1
  flutter_bloc: ^4.0.0
  equatable: ^1.2.0
  meta: ^1.1.6
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.4.0
  firebase_messaging: ^7.0.3
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.5.6+1
  http: ^0.12.1
  async: ^2.4.1
  rflutter_alert: ^1.0.2
  flutter_rating_bar: ^1.1.0
  rating_dialog: ^1.0.0
  quick_feedback: ^0.1.1
  bottom_navy_bar: ^5.4.0
  flutter_money_formatter: ^0.8.3
  bubble_bottom_bar: ^1.2.0
  flutter_multiselect: ^0.0.1
  line_icons: ^0.2.0
  syncfusion_flutter_calendar: ^18.1.45-beta
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  date_picker_timeline: ^1.0.0
  flutter_datetime_picker: ^1.4.0
  custom_switch: ^0.0.1
  intl: ^0.15.8
  lite_rolling_switch: ^0.1.1
  carousel_slider: ^2.3.1
  flutter_switch: ^0.2.0
  flutter_slidable: ^0.5.7
  flushbar: ^1.10.4
  skeleton_text: ^2.0.2
  simple_animations: ^1.3.3
  photo_view: ^0.10.3
  flip_card: ^0.4.4
  dotted_line: ^2.0.2
  getwidget: ^1.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.8.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/bcd-logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 100
          
  assets:
    - assets/






  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
